### ISSUE TITLE
multiple .gz files to unzip at the same time

### ISSUE THREAD

**Issue by r06942072** [NAL-i5K/CWL_Common-Workflow-Language#3]
block_unzip : It can successfully unzip one single <.gz> file
block_unzip_multiple: Hope it can unzip all the <.gz> files in the directory at the same time.

In block_unzip_multiple
I ran the command:
$ cwl-runner --debug unzip.cwl unzip-job.yml

And I got the error message below in my terminal:
Got workflow error
Traceback (most recent call last):
  File "/home/johnbamboobilly/genomics-workspace/py2.7/lib/python2.7/site-packages/cwltool/executors.py", line 148, in run_jobs
    for job in jobiter:
  File "/home/johnbamboobilly/genomics-workspace/py2.7/lib/python2.7/site-packages/cwltool/command_line_tool.py", line 450, in job
    self.updatePathmap(builder.outdir, builder.pathmapper, l)
  File "/home/johnbamboobilly/genomics-workspace/py2.7/lib/python2.7/site-packages/cwltool/command_line_tool.py", line 272, in updatePathmap
    for sf in fn.get("secondaryFiles", []):
AttributeError: 'CommentedSeq' object has no attribute 'get'
Workflow error:
'CommentedSeq' object has no attribute 'get'
Traceback (most recent call last):
  File "/home/johnbamboobilly/genomics-workspace/py2.7/lib/python2.7/site-packages/cwltool/main.py", line 712, in main
    logger=_logger)
  File "/home/johnbamboobilly/genomics-workspace/py2.7/lib/python2.7/site-packages/cwltool/executors.py", line 40, in __call__
    return self.execute(*args, **kwargs)
  File "/home/johnbamboobilly/genomics-workspace/py2.7/lib/python2.7/site-packages/cwltool/executors.py", line 90, in execute
    self.run_jobs(process, job_order_object, logger, runtime_context)
  File "/home/johnbamboobilly/genomics-workspace/py2.7/lib/python2.7/site-packages/cwltool/executors.py", line 175, in run_jobs
    raise WorkflowException(Text(err))
WorkflowException: 'CommentedSeq' object has no attribute 'get'

**Comment by r06942072** [comment]
I think one way to try is to take a Directory as an input, and write in the inputs section of cwl file.
What inside the Directory are files end with extension <.gz>, and we can parse it by InlineJavascriptRequirement. 
for example,  $(inputs.current_dir.listing.basename)
inputs:
  current_dir:
     type: Directory

**Comment by r06942072** [comment]
see block_gunzip #9
